package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientInfo<M extends BaseClientInfo<M>> extends Model<M> implements IBean {

	public void setClientId(java.lang.String clientId) {
		set("client_id", clientId);
	}

	public java.lang.String getClientId() {
		return get("client_id");
	}

	public void setClientSercert(java.lang.String clientSercert) {
		set("client_sercert", clientSercert);
	}

	public java.lang.String getClientSercert() {
		return get("client_sercert");
	}

	public void setClientName(java.lang.String clientName) {
		set("client_name", clientName);
	}

	public java.lang.String getClientName() {
		return get("client_name");
	}

	public void setRedirect(java.lang.String redirect) {
		set("redirect", redirect);
	}

	public java.lang.String getRedirect() {
		return get("redirect");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

}
