package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayStuteInfo<M extends BasePayStuteInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setQrId(java.lang.String qrId) {
		set("qr_id", qrId);
	}

	public java.lang.String getQrId() {
		return get("qr_id");
	}

	public void setAddTime(java.lang.String addTime) {
		set("addTime", addTime);
	}

	public java.lang.String getAddTime() {
		return get("addTime");
	}

	public void setAddTimeStr(java.lang.String addTimeStr) {
		set("addTimeStr", addTimeStr);
	}

	public java.lang.String getAddTimeStr() {
		return get("addTimeStr");
	}

	public void setIsPay(java.lang.Boolean isPay) {
		set("isPay", isPay);
	}

	public java.lang.Boolean getIsPay() {
		return get("isPay");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

}
