package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddMoneryInfo<M extends BaseAddMoneryInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMonery(java.lang.String monery) {
		set("monery", monery);
	}

	public java.lang.String getMonery() {
		return get("monery");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setAddtimeStr(java.lang.String addtimeStr) {
		set("addtimeStr", addtimeStr);
	}

	public java.lang.String getAddtimeStr() {
		return get("addtimeStr");
	}

	public void setAddtime(java.lang.String addtime) {
		set("addtime", addtime);
	}

	public java.lang.String getAddtime() {
		return get("addtime");
	}

}
