package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("PayStuteInfo", "id", PayStuteInfo.class);
		arp.addMapping("addMoneryInfo", "id", AddMoneryInfo.class);
		arp.addMapping("clientInfo", "id", ClientInfo.class);
		arp.addMapping("userInfo", "id", UserInfo.class);
	}
}

