package com.demo.common.model;

import com.demo.common.model.base.BaseAddMoneryInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddMoneryInfo extends BaseAddMoneryInfo<AddMoneryInfo> {
	public static final AddMoneryInfo dao = new AddMoneryInfo();
}
