package com.demo.common.model;


import com.demo.common.model.base.BaseClientInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientInfo extends BaseClientInfo<ClientInfo> {
	public static final ClientInfo dao = new ClientInfo();
}
