package com.demo.common.model;

import com.demo.common.model.base.BasePayStuteInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayStuteInfo extends BasePayStuteInfo<PayStuteInfo> {
	public static final PayStuteInfo dao = new PayStuteInfo();
}
